// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gchfcmykixjjjpurjzgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjaGZjbXlraXhqampwdXJqemdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDkyMzAsImV4cCI6MjA2NTEyNTIzMH0.be5zNox3Qftuiq7aHwmXz4WK7a4M7EF6k14gAALYgXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);